version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      
  build:
    commands:
      - echo "Syncing ./src to s3://$WEBSITE_BUCKET"
      - aws s3 sync "./src" "s3://$WEBSITE_BUCKET"
    finally:
      - echo "Build phase completed `date`"
