version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      
  build:
    commands:
      - echo "Syncing ./src to s3://ci-cd-sample"
      - aws s3 sync "./src" "s3://ci-cd-sample"
    finally:
      - echo "Build phase completed `date`"
